---
- name: Install nginx
  apt: pkg=nginx state=present update_cache=true
  notify:
    - start nginx
- name: copy the index.html file
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
